services:
  client:
    build:
      context: .
      args:
        NEXT_PUBLIC_LOCATIONIQ_KEY: ${NEXT_PUBLIC_LOCATIONIQ_KEY}
        BACKEND_URL: ${BACKEND_URL:-http://backend:8080}
    image: book-store-client:latest
    container_name: book-store-client
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      BACKEND_URL: ${BACKEND_URL:-http://backend:8080}
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    external: true
    name: bookstore-net
